export const SET_PROJECT_MEMBERS = 'SET_PROJECT_MEMBERS';
export const DELETE_PROJECT_MEMBER = 'DELETE_PROJECT_MEMBER';
export const ADD_PROJECT_MEMBER = 'ADD_PROJECT_MEMBER';
export const ADD_PROJECT_SHARE_URL='ADD_PROJECT_SHARE_URL';
export const SET_PROJECT_INVITES='SET_PROJECT_INVITES';
export const ADD_PROJECT_INVITE='ADD_PROJECT_INVITE';
export const DELETE_PROJECT_INVITE='DELETE_PROJECT_INVITE'



