export const SET_AUTOMATIONS="SET_AUTOMATIONS";
export const UPDATE_AUTOMATIONS="UPDATE_AUTOMATIONS";
export const SET_AUTOMATION="SET_AUTOMATION";
export const ADD_AUTOMATION="ADD_AUTOMATION";
export const DELETE_AUTOMATION="DELETE_AUTOMATION";
export const SET_REPOS="SET_REPOS";
export const SET_GITHUB_PROJECTS="SET_GITHUB_PROJECTS";
export const SET_GITHUB_COLUMNS="SET_GITHUB_COLUMNS"

export const SET_REPO_LABELS="SET_REPO_LABELS"

export const SET_REPO_ASSIGNABLEUSERS="SET_REPO_ASSIGNABLEUSERS"
export const SET_ORG_REPO_PROJECTS="SET_ORG_REPO_PROJECTS"
export const SHOW_SET_V3_MILESTONES="SHOW_SET_V3_MILESTONES"
export const SET_REPO_PROJECTS="SET_REPO_PROJECTS"
export const SET_ORG_PROJECTS="SET_ORG_PROJECTS"
