export const SET_PROJECT_FILE = "SET_PROJECT_FILE";
export const  SET_PROJECT_FILES="SET_PROJECT_FILES";
export const ADD_PROJECT_FILE="ADD_PROJECT_FILE";
export const DELETE_PROJECT_FILE="DELETE_PROJECT_FILE";
export const ADD_FILE_PROGRESS="ADD_FILE_PROGRESS";
export const CLEAR_ALL_PROGRESS="CLEAR_ALL_PROGRESS";
export const UPDATE_PROJECT_FILE_NAME = "UPDATE_PROJECT_FILE_NAME";