export const SET_STATUSES = 'SET_STATUSES';
export const ADD_STATUS = 'ADD_STATUS';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const DELETE_STATUS='DELETE_STATUS'

export const SET_SPRINTS = 'SET_SPRINTS';
export const ADD_SPRINT = 'ADD_SPRINT';
export const UPDATE_SPRINT = 'UPDATE_SPRINT';
export const DELETE_SPRINT='DELETE_SPRINT'
export const SET_CURRENT_SPRINT='SET_CURRENT_SPRINT'
export const  SET_SPRINT_CONFIG='SET_SPRINT_CONFIG'