export const SET_SIDEBAR = 'SET_SIDEBAR';
export const SET_CHAT_CLIENT = 'SET_CHAT_CLIENT';
export const SET_CHANNEL = 'SET_CHANNEL';
export const SET_MESSAGES = 'SET_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_RELATION="SET_RELATION";
export const SET_TWILIO_CHANNELS_INIT = 'SET_TWILIO_CHANNELS_INIT';
export const SET_URL_ACTION = 'SET_URL_ACTION';
export const SAVE_ACTIVITIES = 'SAVE_ACTIVITIES';
export const SET_CHECKLIST_ITEMS='SET_CHECKLIST_ITEMS';
export const ADD_CHECKLIST_ITEM='ADD_CHECKLIST_ITEM';
export const UPDATE_CHECKLIST_ITEM=' UPDATE_CHECKLIST_ITEM';
export const DELETE_CHECKLIST_ITEM='DELETE_CHECKLIST_ITEM';
export const DELETE_CHECKLIST='DELETE_CHECKLIST';
export const SET_TASK_COMMENTS='SET_TASK_COMMENTS';
export const ADD_TASK_COMMENT='ADD_TASK_COMMENT';
export const DELETE_TASK_COMMENT = 'DELETE_TASK_COMMENT';

