export const SET_WORKSPACE_TAGS = "SET_WORKSPACE_TAGS";
export const ADD_WORKSPACE_TAGS ="ADD_WORKSPACE_TAGS";
export const UPDATE_WORKSPACE_TAGS="UPDATE_WORKSPACE_TAGS";
export const DELETE_WORKSPACE_TAGS="DELETE_WORKSPACE_TAGS"